Interpretation Asciidoc
======================
Nico Ulsamer, Christina Frei
v1.0
:doctype: article
:toc: right
:toc-title: Inhaltsverzeichnis

[preface]
Vorwort
--------
Im Zuge unseres Deutsch Unterrichts haben wir uns der Analyse der Markup Sprache _Asciidoc_ gewidmet.
Hierzu haben wir unter anderem den direkten Vergleich mit den Funktionen, welche uns Word bietet, angestrebt.

Im Folgendem möchten wir die Vor- und Nachteile von _Asciidoc_ und die möglichen Einsatzgebiete dessen erläutern. Zur Erarbeitung der Funktionen und zur Erstellung dieses Textes wurde AsciidocFX verwendet.


Codebeispiele
------------
Mit den folgenden paar Syntaxkenntnissen kann man bereits Basics in Sachen Formatierung umsetzen.

. Überschriften

Ein einfaches Gleichheitszeichen bewirkt, dass der darauffolgende Text als Hauptüberschrift angesehen und dementsprechend fett geschrieben wird sowie die Schriftgröße höher ausfällt. Je nachdem wie viele Gleichheitszeichen man benutzt, desto stärker wird dieser Effekt reduziert. 

Vergleichbar ist diese Funktion mit den Überschriften in HTML, denn <h1></h1> (HTML) verhält sich wie ein '=' (Asciidoc), sowie <h2></h2> zwei Gleichheitszeichen '==' entsprechen würde.


Vergleich zu MS Office Word 2010
-------------------------------
Auf den ersten Blick lässt sich mit Asciidoc alles so verwirklichen, wie in Word. Jedoch lassen sich mit Word beispielsweise nicht so einfach komplexe mathematische Formeln darstellen.

Editoren
-------
AsciidocFX, Atom, diverse Webeditoren. Selbstverständlich kann man auch mit jedem auf Computern vorinstallierten Editor Asciidoc Dateien erstellen.

Konvertierung in andere Formate
-------------------------------
Um Asciidoc in mehr Arbeitsbereichen verwenden zu können ist es manchmal nötig, dass man die in Asciidoc erstellten Dokumente auch in andere Formate umwandeln kann. Hier wäre vor allem das beliebte pdf-Format zu nennen. Dieses ist beispielsweise praktisch, um seine Arbeit zu verbreiten, ohne dass die Leser sich extra einen Editor herunterladen oder den Text in einen Live Preview Asciidoc Webeditor kopieren müssen.

Anwendungsbeispiele im Betrieb
-----------------------------
Asciidoc eignet sich auch zum Erstellen von Dokumentationen für Programmierarbeiten. 

Bewertung von Asciidoc
---------------------
Zu Beginn möchten wir mit der Bewertung Asciidocs, genauer gesagt dessen Vor- und Nachteilen einleiten.

Vorteile
~~~~~~~~~


[quote,Miguel de Unamuno]
____
Nur indem man das Unerreichbare anstrebt, gelingt das Erreichbare. Nur mit dem Unmöglichen als Ziel, gelingt das Mögliche.
____

Die Vorteile Asciidocs liegen in vielen Bereichen. 
So kann man nicht nur durch einfaches Einfügen von Programmcode und die Angabe der verwendeten Programmiersprache die zugehörige Formatierung ändern, sondern ebenfalls Zitate, Bilder und Tabellen mit Leichtigkeit einfügen.
Dank der Livepreview einiger Programme kann man die verwendeten Bausteine sofort betrachten und gegebenenfalls abändern.

Ein Weiterer, definitiv zu nennender Vorteil von Asciidoc ist die beinahe schon kinderleicht zu handhabende Formatierung, so muss man lediglich einige Codes und Kommandos beherrschen, die es ermöglichen den Text nach den Wünschen des Autors zu formatieren.

Asciidoc bietet, zumindest bei der Benutzung von AsciidocFX die Möglichkeit, Dokumente als Ebook, Docbook, HTML oder PDF auszugeben.

Des Weiteren lassen sich mit ein paar Zeichen schon komplexe mathematische Formeln darstellen, so lässt sich durch Verwendung von zwei Zirkumflexen eine Potenz darstellen. Mit der Nutzung zweier Tilde kann man eine Zahl mit einem Index versehen. 
[source, Asciidoc]
----
Beispiel: x^2^ ; x~2~dsaf
----
Formatiert sieht das dann so aus:** x^2^ ; x~2~**

Nachteile
~~~~~~~~
Zu nennende Nachteile sind unter anderem das Fehlen einer Autokorrektur(was wiederrum mit dem Editor zusammenhängt, jedoch fanden wir keinen, bei dem eine Autokorrektur vorhanden war) und, dass, sobald etwas über Copy & Paste eingefügt wird, es sofort als Java Code interpretiert wird und somit erst die zwei generierten Codezeilen gelöscht werden müssen.

Leider gibt es kaum deutsche Nachschlagewerke (Cheatsheets etc.).

Keine mögliche Konfiguration vorgefertigter Zeichensätze (Länge von Pfeilen, Lage von Pfeilen etc.)

Zu den Nachteilen zählt außerdem die Tatsache, dass man durch versehentliche Returns oder Sonderzeichen die gesamte Formatierung verändern kann, wodurch das Dokument ungewollt anders aussieht. 

Fazit
----

